function converted_names = convert_varnames(varnames)
    % Check for nominal or present value indicators and modify names accordingly
    is_nominal = endsWith(varnames, "_n");
    is_present = endsWith(varnames, "_p");
    
    % Remove the _n and _p suffixes before dictionary lookup
    varnames_clean = varnames;
    varnames_clean(is_nominal) = extractBefore(varnames(is_nominal), "_n");
    varnames_clean(is_present) = extractBefore(varnames(is_present), "_p");

    converter = dictionary( ...
        ["adv_cap", "prototype_RD", "benefits", "inp_cap", "inp_marg", "inp_RD", "inp_tail", ...
         "m_learning_losses", "m_deaths", "m_mortality_losses", "m_output_losses", "surveil", "u_deaths", ...
         "advance_capacity", "advance_rd", "neglected_pathogen_rd", "improved_early_warning", "combined_invest", "baseline", "ufv_RD", ...
         "universal_flu_rd"], ...
        ["Advance capacity", "Advance R&D", "Benefits (present value)", "Response capacity", "Vaccination unit costs", ...
         "Response R&D", "Tailoring costs", "Learning losses (present value)", "Deaths", "Mortality losses", ...
         "Economic losses", "Improved early warning costs", "Unmitigated deaths", ...
         "Advance capacity", "Neglected disease R&D", "Neglected disease R&D", "Improved early warning", "Combined", "Baseline", "Universal flu vaccine R&D", ...
         "Universal flu vaccine R&D"] ...
    );

    % Add nominal/present value indicators to names after dictionary lookup
    converted_names = converter(varnames_clean);
    converted_names(is_nominal) = converted_names(is_nominal) + " (nominal value)";
    converted_names(is_present) = converted_names(is_present) + " (present value)";
end