function non_baseline_only_fields = get_non_baseline_fields()
    % Sensitivity override fields considered safe to reuse baseline across.
    % Any field not listed here is treated as potentially baseline-affecting,
    % causing a baseline rerun for that sensitivity value.
    non_baseline_only_fields = { ...
        'scenario_configs', ...
        'adv_cap_reference', ...
        'tailoring_fraction', ...
        'adv_cap_build_period', ...
        'prototype_effect_ptrs', ...
        'advance_RD_cost_per_pathogen', ...
        'advance_RD_benefit_start', ...
        'univ_flu_vax_eff_multiplier', ...
        'univ_flu_cost_multiplier', ...
        'prototype_success_prob', ...
        'ufv_success_prob', ...
        'initial_share_ufv', ...
        'ew_annual_cost', ...
    };
end
