function save_to_file_fast(scenario_name, outdirpath, sim_results, ...
    sim_out_arr_costs_adv_cap_nom, sim_out_arr_costs_adv_cap_PV, ...
    sim_out_arr_costs_prototype_RD_nom, sim_out_arr_costs_prototype_RD_PV, ...
    sim_out_arr_costs_ufv_RD_nom, sim_out_arr_costs_ufv_RD_PV, ...
    sim_out_arr_costs_surveil_nom, sim_out_arr_costs_surveil_PV, ...
    sim_out_arr_costs_inp_cap_nom, sim_out_arr_costs_inp_cap_PV, ...
    sim_out_arr_costs_inp_marg_nom, sim_out_arr_costs_inp_marg_PV, ...
    sim_out_arr_costs_inp_tailoring_nom, sim_out_arr_costs_inp_tailoring_PV, ...
    sim_out_arr_costs_inp_RD_nom, sim_out_arr_costs_inp_RD_PV, ...
    sim_out_arr_u_deaths, sim_out_arr_m_deaths, ...
    sim_out_arr_m_mortality_losses, sim_out_arr_m_output_losses, ...
    sim_out_arr_learning_losses, sim_out_arr_benefits_vaccine, ...
    sim_out_arr_benefits_vaccine_nom)
    %SAVE_TO_FILE_FAST Save all model outputs to a single MAT file for speed.
    %
    %   This function saves all simulation results to a single MAT file instead
    %   of multiple CSV files, which is much faster for large datasets.

    fprintf('Saving results to single MAT file...\n');

    % Create output filename
    mat_filename = sprintf('%s/%s_results.mat', outdirpath, scenario_name);

    % Save everything to a single MAT file (much faster than multiple CSVs)
    save(mat_filename, 'sim_results', ...
        'sim_out_arr_costs_adv_cap_nom', 'sim_out_arr_costs_adv_cap_PV', ...
        'sim_out_arr_costs_prototype_RD_nom', 'sim_out_arr_costs_prototype_RD_PV', ...
        'sim_out_arr_costs_ufv_RD_nom', 'sim_out_arr_costs_ufv_RD_PV', ...
        'sim_out_arr_costs_surveil_nom', 'sim_out_arr_costs_surveil_PV', ...
        'sim_out_arr_costs_inp_cap_nom', 'sim_out_arr_costs_inp_cap_PV', ...
        'sim_out_arr_costs_inp_marg_nom', 'sim_out_arr_costs_inp_marg_PV', ...
        'sim_out_arr_costs_inp_tailoring_nom', 'sim_out_arr_costs_inp_tailoring_PV', ...
        'sim_out_arr_costs_inp_RD_nom', 'sim_out_arr_costs_inp_RD_PV', ...
        'sim_out_arr_u_deaths', 'sim_out_arr_m_deaths', ...
        'sim_out_arr_m_mortality_losses', 'sim_out_arr_m_output_losses', ...
        'sim_out_arr_learning_losses', 'sim_out_arr_benefits_vaccine', ...
        'sim_out_arr_benefits_vaccine_nom', ...
        '-v7.3');

    fprintf('Saved all results to %s\n', mat_filename);

    % Optionally save just the main results table as CSV for compatibility
    csv_filename = sprintf('%s/%s_pandemic_table.csv', outdirpath, scenario_name);
    writetable(sim_results, csv_filename);
    fprintf('Saved results table to %s\n', csv_filename);
end