function save_to_file_fast(scenario_name, outdirpath, pandemic_table, ...
    sim_out_arr_costs_adv_cap_nom, sim_out_arr_costs_adv_cap_PV, ...
    sim_out_arr_costs_prototype_RD_nom, sim_out_arr_costs_prototype_RD_PV, ...
    sim_out_arr_costs_ufv_RD_nom, sim_out_arr_costs_ufv_RD_PV, ...
    sim_out_arr_costs_surveil_nom, sim_out_arr_costs_surveil_PV, ...
    sim_out_arr_costs_inp_cap_nom, sim_out_arr_costs_inp_cap_PV, ...
    sim_out_arr_costs_inp_marg_nom, sim_out_arr_costs_inp_marg_PV, ...
    sim_out_arr_costs_inp_tailoring_nom, sim_out_arr_costs_inp_tailoring_PV, ...
    sim_out_arr_costs_inp_RD_nom, sim_out_arr_costs_inp_RD_PV, ...
    total_costs_nom, total_costs_pv, ...
    sim_out_arr_u_deaths, sim_out_arr_m_deaths, ...
    sim_out_arr_m_mortality_losses, sim_out_arr_m_output_losses, ...
    sim_out_arr_learning_losses, sim_out_arr_benefits_vaccine, ...
    sim_out_arr_benefits_vaccine_nom)
    % SAVE_TO_FILE_FAST Save all model outputs to a single MAT file for speed.
    %
    %   This function saves all simulation results to a single MAT file instead
    %   of multiple CSV files, which is much faster for large datasets.

    fprintf('Saving results...\n');
    if ~exist(outdirpath, 'dir')
        mkdir(outdirpath);
    end
    
    annual_results_file = fullfile(outdirpath, sprintf('%s_results.mat', scenario_name));
    pandemic_table_mat_file = fullfile(outdirpath, sprintf('%s_pandemic_table.mat', scenario_name));

    % Save everything to a single MAT file (much faster than multiple CSVs)
    % Pack into a struct (clean + a bit faster)
    S = struct( ...
        'costs_adv_cap_nom',                  sim_out_arr_costs_adv_cap_nom, ...
        'costs_adv_cap_PV',                   sim_out_arr_costs_adv_cap_PV, ...
        'costs_prototype_RD_nom',             sim_out_arr_costs_prototype_RD_nom, ...
        'costs_prototype_RD_PV',              sim_out_arr_costs_prototype_RD_PV, ...
        'costs_ufv_RD_nom',                   sim_out_arr_costs_ufv_RD_nom, ...
        'costs_ufv_RD_PV',                    sim_out_arr_costs_ufv_RD_PV, ...
        'costs_surveil_nom',                  sim_out_arr_costs_surveil_nom, ...
        'costs_surveil_PV',                   sim_out_arr_costs_surveil_PV, ...
        'costs_inp_cap_nom',                  sim_out_arr_costs_inp_cap_nom, ...
        'costs_inp_cap_PV',                   sim_out_arr_costs_inp_cap_PV, ...
        'costs_inp_marg_nom',                 sim_out_arr_costs_inp_marg_nom, ...
        'costs_inp_marg_PV',                  sim_out_arr_costs_inp_marg_PV, ...
        'costs_inp_tailoring_nom',            sim_out_arr_costs_inp_tailoring_nom, ...
        'costs_inp_tailoring_PV',             sim_out_arr_costs_inp_tailoring_PV, ...
        'costs_inp_RD_nom',                   sim_out_arr_costs_inp_RD_nom, ...
        'costs_inp_RD_PV',                    sim_out_arr_costs_inp_RD_PV, ...
        'total_costs_nom',                    total_costs_nom, ...
        'total_costs_pv',                     total_costs_pv, ...
        'u_deaths',                           sim_out_arr_u_deaths, ...
        'm_deaths',                           sim_out_arr_m_deaths, ...
        'm_mortality_losses',                 sim_out_arr_m_mortality_losses, ...
        'm_output_losses',                    sim_out_arr_m_output_losses, ...
        'learning_losses',                    sim_out_arr_learning_losses, ...
        'benefits_vaccine',                   sim_out_arr_benefits_vaccine, ...
        'benefits_vaccine_nom',               sim_out_arr_benefits_vaccine_nom);

    save(annual_results_file, '-struct', 'S', '-v7.3');  % single call = fastest for v7.3
    fprintf('Saved annual results to %s\n', annual_results_file);

    % Save the pandemic table as a MAT file as well
    save(pandemic_table_mat_file, 'pandemic_table', '-v7.3');
    fprintf('Saved pandemic table to %s\n', pandemic_table_mat_file);
end