function validate_run_config(config, caller)
    % Validate a job configuration struct loaded from YAML.
    %
    % Errors immediately on any missing required field. Does NOT error on
    % unknown fields (forward-compatible). Call this near the top of any
    % entry-point script that accepts a job config.
    %
    % Args:
    %   config (struct): Job config loaded via yaml.loadFile.
    %   caller (char, optional): Name of the calling script, used in error
    %       messages. Defaults to 'validate_run_config'.
    %
    % Example:
    %   run_config = yaml.loadFile(run_config_path);
    %   validate_run_config(run_config, 'run_job');

    if nargin < 2
        caller = 'validate_run_config';
    end

    % Fields required by every job-config entry point.
    core_required = { ...
        'outdir', ...
        'num_simulations', ...
        'sim_periods', ...
        'seed', ...
        'arrival_dist_config', ...
        'duration_dist_config', ...
        'arrival_rates', ...
        'pathogen_info', ...
        'econ_loss_model_config', ...
        'y', ...
        'r', ...
        'P0', ...
        'Y0', ...
        'value_of_death', ...
    };

    % Additional fields required only by run_job (full response model).
    run_job_required = { ...
        'scenario_configs', ...
        'ptrs_pathogen', ...
        'prototype_effect_ptrs', ...
        'rd_timelines', ...
        'response_threshold_path', ...
        'tolerance', ...
        'save_mode', ...
        'pandemic_table_out', ...
    };

    check_fields(config, core_required, caller);

    if isfield(config, 'scenario_configs')
        % If scenario_configs is present, treat this as a run_job config
        % and validate the full set of required fields.
        check_fields(config, run_job_required, caller);
    end
end


function check_fields(config, required_fields, caller)
    missing = {};
    for i = 1:numel(required_fields)
        if ~isfield(config, required_fields{i})
            missing{end+1} = required_fields{i}; %#ok<AGROW>
        end
    end
    if ~isempty(missing)
        error('%s:MissingConfigFields', caller, ...
            'Job config is missing required field(s): %s\nCheck config/README.md for the full field reference.', ...
            strjoin(missing, ', '));
    end
end
