# Run params
num_simulations: 1000000
sim_periods: 200
outdir: "./output/jobs"
scenario_configs: "./config/scenario_configs/pairwise_combos_surplus"
seed: 42
add_datetime_to_outdir: 0
save_output: 1
profile: false # Profile main parallel loop
pandemic_table_out: "full" # Full, skinny, or none
save_mode: "light"
tolerance: 9e-4 # Make zero in out arrays

# Social value
y: 0.016 # Growth rate
r: 0.04 # Social discount rate
P0: 8.14e9 # Base year population (2024, World Bank)
Y0: 13673 # Base year GDP, 2024 World Bank
value_of_death: 1.3e6
conservative: 1 # Whether harm avoided is calculated at beginning (conservative) or end of period (not conservative)
gamma: 0.5 # fraction of remaining harm mitigated by vaccine

# Pandemic params
response_threshold_path: "./output/response_thresholds/response_threshold_half_covid_severity.yaml" # Response threshold in terms intensity
arrival_dist_config: "output/arrival_distributions/modified/gpd_all_excl_unid_filt_intensity_fit_severity_0d01_1900_poisson_sharp_upper_200_n_1000000_seed_42"
duration_dist_config: "./output/duration_distributions/clean_filt_all_int_0d01_1900_mod_trunc_10_n_1000000_seed_42.csv"
arrival_rates: "./data/clean/arrival_rates_all.csv"
econ_loss_model_config: "./output/econ_loss_models/poisson_model_total_severity.yaml"

# Capacity
theta: 0.25 # Max surge capacity displacement due to advance capacity
max_capacity: 24.23e9 # Maximum capacity in annual courses
delta: 0.19 # Annual maintenance cost as fraction of capital value
mRNA_share: 0.5 # Share capacity that is mRNA.
capacity_kept: 0.5 # Share response capacity kept after a pandemic
k_m: 1.5 # Per course cost of mRNA capacity ($/course)
k_o: 3 # Per course cost of traditional capacity ($/course)
tailoring_fraction: 0.33 # Share capital cost paid at pandemic onset.
c_m: 34 # marginal cost of producing mRNA vaccines ($ per course) (LB)
c_o: 17 # marginal cost of producing traditional vaccines ($ per course) (LB)
epsilon: 1 # decreasing returns to capacity investments during pandemic
beta: 100e6 # in-pandemic kink in capital cost function
base_cap_mrna: 2.53e9 # Annual courses baseline mRNA capacity. From expert survey.
base_cap_trad: 5.84e9 # Annual courses baseline traditional capacity. Adding capacity egg-based and other platforms in expert survey.
surge_cap_mrna: 2.25e9 # Surge capacity in mRNA platform
surge_cap_trad: 2.25e9 # Surge capacity in traditional platform
f_m: 0.3 # fraction of at risk capacity successful in mRNA platform
f_o: 0.3 # fraction of at risk capacity successful in traditional platform
g_m: 0.4 # fraction of at risk capacity unsuccessful/repurpose-able in mRNA platform
g_o: 0.4 # fraction of at risk capacity unsuccessful/repurpose-able in traditional platform
adv_cap_build_period: 30 # number of years it takes to establish capacity reservation

# Vaccine development
pathogen_info: "./data/raw/pathogen_info.csv"
ptrs_pathogen: "./output/ptrs/ptrs_table.csv" # Pathogen vaccine probability of success
prototype_effect_ptrs: "./output/ptrs/prototype_effect_preds.csv" # Probability of success across has and no advanced R&D. Used to calibrate improvement in probability from advanced R&D.
rd_timelines: "./output/rd_timelines/timelines_from_predictions.csv" # Current deprecated
tau_m: 2 # months to repurpose mRNA capacity
tau_o: 8 # months to repurpose traditional capacity
inp_RD_spend: 6.86e9 # $
frac_invest_on_false: 0.33 # Wasted expenditure on false positive.
advance_RD_cost_per_pathogen: 1.06e9 # $ in 2024 use, see write_adv_rd_inputs.R
advance_RD_benefit_start: 11 # years until advance R&D benefits apply
univ_flu_vax_eff_multiplier: 0.5 # Multiplier on universal flu vaccine effectiveness
rd_months_with_prototype: 11 # In-pandemic R&D timeline with prototype (months)
rd_months_no_prototype: 18 # In-pandemic R&D timeline without prototype (months)
univ_flu_cost_multiplier: 2 # Multiplier on universal flu vaccine cost
prototype_success_prob: 0.9 # Probability of prototype working if it is invested in
ufv_success_prob: 0.9 # Probability of universal flu vaccine success

# Surveillance
surveil_annual_installation_spend: 490e6 # Initial spending to install enhanced surveillance
surveil_installation_years: 2 # Time initial costs are incurred
surveil_maintenance_spend: 490e6 # Maintenance spending on enhanced surveillance
months_to_early_detect: 1
months_to_regular_detect: 2
base_early_detect_prob_true: 0.66
base_early_detect_prob_false: 0
inc_early_detect_prob_true: 0.2
inc_early_detect_prob_false: 0.1
