# Run params
num_simulations: 10000
sim_periods: 200
outdir: "./output"
scenario_configs: "./config/scenario_configs/test"
seed: 42
include_false_positives: 0
add_datetime_to_outdir: 0
sim_scens_path: null # Load previously created pandemic simulations (rather than creating new ones with parameters below)
save_output: 1
endogenous_rental: 0

# Social value
y: 0.016 # Growth rate
r: 0.04 # Social discount rate
P0: 7.91e9 # Base year population (2021)
Y0: 12316.1 # Base year GDP
value_of_death: 1.3e6
conservative: 1 # Whether harm avoided is calculated at beginning (conservative) or end of period (not conservative)
gamma: 0.5 # fraction of remaining harm mitigated by vaccine

# Pandemic params
response_threshold: 0.16 # Half of COVID-19 intensity (0.32 deaths per 1000 per year)
arrival_dist_config: "./pandemic-loss-modeling/output/arrival_distributions/all_risk_default.yaml"
duration_dist_config: "./pandemic-loss-modeling/output/duration_distributions/all_risk_default.yaml"
viral_family_data: "./data/clean/vf_data_arrival_select.csv"
econ_loss_model_config: "./pandemic-loss-modeling/output/econ_loss_models/poisson_model.yaml"

# Capacity
theta: 0.25 # Fraction reduction in pandemic-time investments due to advance capacity
delta: 0.19 # Annual maintenance cost as fraction of capital value
mRNA_share: 0.5 # Share capacity that is mRNA.
capacity_kept: 0.5 # Share response capacity kept after a pandemic
k_m: 1.5 # Per course cost of mRNA capacity ($/course)
k_o: 3 # Per course cost of traditional capacity ($/course)
tailoring_fraction: 0.33 # Share capital cost paid at pandemic onset.
c_m: 34 # marginal cost of producing mRNA vaccines (LB per course)
c_o: 17 # marginal cost of producing traditional vaccines (LB per course)
epsilon: 1 # decreasing returns to capacity installed during pandemic
beta: 100e6 # in-pandemic kink in capital cost function
x_target: 15.7e9 # target total capacity in annual courses (x^{\prime\prime} in paper)
x_avail: 4.51e9 # total capacity in annual courses that can be achieved in pandemic (x^\prime in paper)
f_m: 0.2 # fraction of at risk capacity successful in mRNA platform
f_o: 0.2 # fraction of at risk capacity successful in traditional platform
g_m: 0.4 # fraction of at risk capacity unsuccessful/repurpose-able in mRNA platform
g_o: 0.4 # fraction of at risk capacity unsuccessful/repurpose-able in traditional platform
rental_share: 0.4 # Share maintenance cost recuperated from pandemic in absence of rental.
adv_cap_build_period: 30 # number of years it takes to finish building adv capacity

# Vaccine development
p_b: 0.25 # prob both technologies are successful
p_m: 0.075 # prob only mRNA successful
p_o: 0.075 # prob only traditional platform successful
tau_A: 14 # months to approve / prep for vaccination campaign (in status quo, is it tau_A + 1, as surveillance generates possibility of one month quicker)
tau_m: 2 # months to repurpose mRNA candidate
tau_o: 6 # months to repurpose traditional candidate
pathogens_per_family: 3 # Number of families to research to obtain R&D benefits for one family.
inp_RD_no_adv_RD: 0.776297560 # bn of nominal
inp_RD_with_adv_RD: 0.531221781 # bn of nominal
adv_RD_cost_per_pathogen: 1.4 # in billion, nominal over period specified by adv_RD_benefit_start (Dimitrios said to use 3x 1.4 bn, times number of families)
adv_RD_benefit_start: 15 # years until advance R&D benefits apply

# Surveillance
surveillance_thresholds: [0, 0] # First is for regular signal, second is for enhanced surveillance signal.
surveil_annual_installation_spend: 5 # Initial spending to install enhanced surveillance, nom bn
surveil_installation_years: 2 # Time initial costs are incurred, nom bn
surveil_maintenance_spend: 1.25 # Maintenance spending on enhanced surveillance nom bn