function sim_scens_path = gen_all_sim_scens(arrival_dist_params, include_false_positives, sim_cnt, ...
	i_star_threshold, viral_family_frequency_table, sim_periods, outdirpath)

	arrival_dist = ArrivalDist(arrival_dist_params.dist_family, ...
		arrival_dist_params.min_severity_exceed_prob, ...
		arrival_dist_params.min_severity, ...
		arrival_dist_params.max_severity, ...
		arrival_dist_params.dist_params);
	
	int_matrix_path = gen_severity_matrix(arrival_dist, include_false_positives, sim_cnt, sim_periods, outdirpath); 
	sim_scens_path = gen_sim_scens_new(include_false_positives, i_star_threshold, viral_family_frequency_table, int_matrix_path, outdirpath);

end