# Config for sensitivity analysis on baseline and advance investment vaccine programs.
base_job_config: "./config/job_configs/allrisk_base_medium.yaml"
outdir: "./output/sensitivity"
fix_params: # Parameters to update and fix in the base config
  scenario_configs: "./config/scenario_configs/baseline"
sensitivities:
  # Vaccine-supply parameters
  gamma:  # Fraction remaining harm mitigated by vaccine
    - 0.3    # 30%
    - 0.7    # 70%

  capacity_kept: # Share response capacity kept after a pandemic
    - 0.25
    - 0.75
  
  k_m:  # Unit cost of advance mRNA capacity
    - 0.75   # $0.75 per annual course
    - 5.0    # $3.00 per annual course
  
  k_o:  # Unit cost of advance capacity for other vaccines
    - 1.5    # $1.50 per annual course
    - 6.0    # $6.00 per annual course
  
  c_m:  # Marginal cost of producing mRNA vaccines
    - 20.0   
    - 40.0    
  
  c_o:  # Marginal cost of producing other vaccines
    - 12    # $1.50 per course
    - 30    # $6.00 per course
  
  epsilon:  # Decreasing returns to pandemic capacity
    - 0.75   # 0.75
    - 1.25   # 1.25
  
  f_m:  # Fraction of at-risk capacity successful in mRNA
    - 0.15    # 20%
    - 0.5    # 40%
  
  f_o:  # Fraction of at-risk capacity successful in traditional
    - 0.15    # 20%
    - 0.5    # 40%
  
  g_m:  # Fraction of at-risk capacity repurposable in mRNA
    - 0.2    # 20%
    - 0.6    # 60%
  
  g_o:  # Fraction of at-risk capacity repurposable in traditional
    - 0.2    # 20%
    - 0.6    # 60%
  
  tau_m:  # Time to repurpose mRNA capacity
    - 1      # 1 month
    - 3      # 3 months
  
  tau_o:  # Time to repurpose other capacity
    - 3      # 3 months
    - 9      # 9 months

  duration_dist_config:
    - "output/duration_distributions/clean_filt_all_int_0d01_1900_mod_trunc_20_n_250000_seed_42.csv"
    - "output/duration_distributions/clean_filt_all_int_0d01_1900_mod_trunc_50_n_250000_seed_42.csv"

  rd_timelines:
    - "output/rd_timelines/optimistic_rd_timelines.csv"
    - "output/rd_timelines/optimistic_rd_timelines.csv"

  ptrs_pathogen:
    - "output/ptrs/marginal_ptrs_preds_always_succeed.csv"