# Config for sensitivity analysis on baseline and advance investment vaccine programs.
base_run_config: "./config/run_configs/airborne_base.yaml"
outdir: "./output/sensitivity_runs"
fix_params: # Parameters to update and fix in the base config
  scenario_configs: "./config/scenario_configs/baseline"
sensitivities:
  ptrs_pathogen_gamma1:   # scenario name (folder under run_name)
    ptrs_pathogen: "./data/clean/ptrs_table_always_succeed.csv"
    gamma: 1