base_job_config: "./config/job_configs/no_mitigation.yaml"
outdir: "./output/sensitivity"
fix_params:
sensitivities:
  vary_severity_dist:
    severity_dist_config: "./output/severity_distributions/genpareto_all_risk_trunc_spflu.yaml"
  vary_econ_loss:
    econ_loss_model_config: "./output/econ_loss_models/loglog_model.yaml"
  both:
    severity_dist_config: "./output/severity_distributions/genpareto_all_risk_trunc_spflu.yaml"
    econ_loss_model_config: "./output/econ_loss_models/loglog_model.yaml"
  

