base_run_config: "./config/run_configs/allrisk_base.yaml"
outdir: "./output/sensitivity_runs"
fix_params:
  gamma: 0
  scenario_configs: "./config/scenario_configs/baseline"
  response_threshold: 0
  response_threshold_type: "severity"
sensitivities:
  severity_trunc_1000:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c__filt__all_int_0d01_1900__arr__gpd_severity_poisson_sharp_u1000_n1000000_s42"
  severity_trunc_10000:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c_upcov__filt__all_int_0d01_1900__arr__gpd_severity_poisson_sharp_u1000_n1000000_s42"
  lower_sev_threshold_1:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c_upcov__filt__all_int_1d0_1900__arr__gpd_severity_poisson_sharp_u10000_n1000000_s42"
  airborne_only:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c_upcov__filt__airborne_int_0d01_1900__arr__gpd_severity_poisson_sharp_u200_n1000000_s42"
    duration_dist_config: "data/clean/duration_distributions/e241210c_upcov__filt__airborne_int_0d01_1900__dur__trunc10_n1000000_s42.csv"
  year_min_1950:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c_upcov__filt__all_int_0d01_1950__arr__gpd_severity_poisson_sharp_u200_n1000000_s42"
    duration_dist_config: "data/clean/duration_distributions/e241210c_upcov__filt__all_int_0d01_1950__dur__trunc10_n1000000_s42.csv"
  include_unid:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c_upcov__filt__all_int_0d01_1900_incl_unid__arr__gpd_severity_poisson_sharp_u200_n1000000_s42"
    duration_dist_config: "data/clean/duration_distributions/e241210c_upcov__filt__all_int_0d01_1900_incl_unid__dur__trunc10_n1000000_s42.csv"
  include_unid_yearthreshonly:
    arrival_dist_config: "data/clean/arrival_distributions/e241210c_upcov__filt__all_int_0d01_1900_yearthreshonly_incl_unid__arr__gpd_severity_poisson_sharp_u200_n1000000_s42"
    duration_dist_config: "data/clean/duration_distributions/e241210c_upcov__filt__all_int_0d01_1900_yearthreshonly_incl_unid__dur__trunc10_n1000000_s42.csv"
  value_of_death:
    - 1e6
    - 1.6e6
  y:
    - 0.014
    - 0.018
  r:
    - 0.02
    - 0.06
