base_job_config: "./config/job_configs/allrisk_base.yaml"
outdir: "./output/sensitivity"
fix_params:
  gamma: 0
  scenario_configs: "./config/scenario_configs/standard/baseline.yaml"
sensitivities:
  arrival_dist_config:
    - "output/arrival_distributions/modified/gpd_all_excl_unid_filt_intensity_fit_severity_0d01_1900_poisson_sharp_upper_1000_n_250000_seed_42"
    - "output/arrival_distributions/modified/gpd_all_excl_unid_filt_intensity_fit_severity_0d01_1900_poisson_sharp_upper_10000_n_250000_seed_42"
    - "output/arrival_distributions/modified/gpd_all_excl_unid_filt_intensity_fit_severity_1d0_1900_poisson_sharp_upper_200_n_250000_seed_42"
    - "output/arrival_distributions/modified/gpd_airborne_excl_unid_filt_intensity_fit_severity_0d01_1900_poisson_sharp_upper_200_n_250000_seed_42"
  value_of_death:
    - 1e6
    - 1.6e6
  y:
    - 0.014
    - 0.018
  r:
    - 0.02
    - 0.06
