neglected_pathogen_rd:
  strategy: top
  num: 1
universal_flu_rd:
  active: true
  platform_response_invest: both
  initial_share_ufv: 0
advance_capacity:
  share_target_advance_capacity: 0
improved_early_warning:
  active: false
  precision: null
  recall: null
