# Neglected pathogen family advance R&D params
neglected_pathogen_rd: 
  strategy: none
  num: 0

# Universal flu vaccine R&D params
universal_flu_rd:
  active: false
  platform_response_invest: null
  initial_share_ufv: null 

# Advance capacity params
advance_capacity:
  share_target_advance_capacity: 0.5

# Enhanced surveillance
improved_early_warning:
  active: false
  precision: null
  recall: null
