# Neglected viral family advance R&D params
rd_investments: 
  strategy: none
  num: 0

# Universal flu vaccine R&D params
ufv_invest: false
initial_share_ufv: 0.5

# Advance capacity params
share_target_advanced_capacity: 0

# Enhanced surveillance
enhanced_surveillance: false
early_detect_prob_true: 0.66
early_detect_prob_false: 0
