# Advance R&D params
rd_speedup_months: 12 # how much tau_A is shortened by with advance R&D (months)
rd_investments: 
  strategy: none
  num: 0

# Advance capacity params
share_target_advanced_capacity: 0

# Enhanced surveillance
enhanced_surveillance: true
