# Neglected pathogen advance R&D params
rd_investments: 
  strategy: none
  num: 0

# Universal flu vaccine R&D params
ufv_invest: false
initial_share_ufv: 0.1 # 850 million projected flu vaccine demand (WHO) / World Bank global pop 2024

# Advance capacity params
share_target_advanced_capacity: 0

# Enhanced surveillance
improved_early_warning: true
