madhav_exceedances = readtable("./data/raw/madhav_et_al_figure_4_digitized.csv", ...
    'HeaderLines', 2);

madhav_exceedances.Properties.VariableNames = {'severity_central', 'exceedance_central', ...
                                               'severity_upper', 'exceedance_upper', ...
                                               'severity_lower', 'exceedance_lower'};

writetable(madhav_exceedances, "./data/clean/madhav_et_al_severity_exceedance.csv");